// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMvxr2Jdw3v8RULaXDPSzqqE1JGXmhuE',
    appId: '1:453910897254:web:5fcf7ac2df3baeb89303a7',
    messagingSenderId: '453910897254',
    projectId: 'genie-blockchain-eaaf4',
    authDomain: 'genie-blockchain-eaaf4.firebaseapp.com',
    storageBucket: 'genie-blockchain-eaaf4.appspot.com',
    measurementId: 'G-L0XXYEGRBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq6Kt9xMRwIK4jsCOf3iO0GNhwYMzLw20',
    appId: '1:453910897254:android:81048f79b982e5289303a7',
    messagingSenderId: '453910897254',
    projectId: 'genie-blockchain-eaaf4',
    storageBucket: 'genie-blockchain-eaaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Qjr0swFcd7hzlI2zqlapxe9edpwVVxk',
    appId: '1:453910897254:ios:f50647108efac3fc9303a7',
    messagingSenderId: '453910897254',
    projectId: 'genie-blockchain-eaaf4',
    storageBucket: 'genie-blockchain-eaaf4.appspot.com',
    iosClientId:
        '453910897254-5j8jcsp1hcclf5t38hc5rd81cej77t4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.genie',
  );
}
